### ISSUE TITLE
[BACK] Desenvolver API para a seção "Home"

### ISSUE THREAD

**Issue by JeanCHilger** [FronteiraTec/event-manager-uffs#16]
Esta issue é uma subtarefa da issue #8.

Desenvolver a API (REST) para gerenciar a seção "Home" (como a primeira seção da [sacc](http://uffs.cc/sacc/))

Especificação da API:

- Nome do model:
  - `HomeSection`;
- Atributos:
  - `title` (String);
  - `subtitle_1` (String, opicional): destinado ao nome do curso;
  - `subtitle_2` (String): destinado aos dias em que o evento ocorrerá;
  - `subtitle_3` (String): destinado ao local do evento;

**Comment by JeanCHilger** [comment]
Talvez devêssemos colocar nomes mais significativos do que `subtitle_<n>`?

**Comment by mateusKoppe** [comment]
> Talvez devêssemos colocar nomes mais significativos do que `subtitle_<n>`?

Também acho uma boa, poderíamos nomear de acordo com o que representam, por exemplo `courseName`, `dateStart`, `dateEnd`, `location` ou algo nesse sentido. 
O que acha?

**Comment by mateusKoppe** [comment]
Acabei de conferir outras issues e vi que praticamente os mesmos campos foram definidos na issue de evento, agora fiquei com um pouco em dúvida sobre os `subtitle_<n>` nessa issue

**Comment by JeanCHilger** [comment]
É que eu tinha colocado `subtitle_<n>` por que o usuário poderia escrever qualquer coisa nesses campos, o curso, local etc seria uma sugestão pra ele apenas.

**Comment by mateusKoppe** [comment]
Como os requisitos do sistema mudou vou fechar essa issue.
