### ISSUE TITLE
[FRONT] Desenvolver frontend para a seção "Home"

### ISSUE THREAD

**Issue by JeanCHilger** [FronteiraTec/event-manager-uffs#19]
Esta issue é uma subtarefa da issue #8.

Desenvolver o frontend que será responsável por criar/editar a seção e por renderizá-la na página do evento, consumindo a API da issue #16. Layout pode ser baseado no [sacc](http://uffs.cc/sacc/)

**Comment by mateusKoppe** [comment]
Como os requisitos do sistema mudou vou fechar essa issue.
