### ISSUE TITLE
Link da documentação das tecnologias usadas

### ISSUE THREAD

**Issue by arufonsekun** [FronteiraTec/event-manager-uffs#2]
- [Bootstrap](https://getbootstrap.com/docs/4.2/getting-started/introduction/)
- [Laravel](https://laravel.com/)
- [Vuejs](https://vuejs.org/v2/guide/)

**Comment by mateusKoppe** [comment]
Bora adicionar esses links no README e aí podemos fechar essa issue?

**Comment by arufonsekun** [comment]
Ficarei com essa _issue_

**Comment by JeanCHilger** [comment]
Esta issue será fechada, pois o link das documentações foi adicionado no README
