### ISSUE TITLE
[BACK] Login utilizando o IdUFFS

### ISSUE THREAD

**Issue by arufonsekun** [FronteiraTec/event-manager-uffs#20]
- Implementar a lógica do login utilizando o IdUffs;
 - Uma opção é utilizar essa package [auth-iduffs](https://github.com/ccuffs/auth-iduffs);

**Comment by Dovyski** [comment]
Eu posso trabalhar nessa issue. Estou criando uma API da UFFS para integrar vários serviços. Começar aqui é um ótimo teste.

Qual o prazo para concluir essa issue?

**Comment by mateusKoppe** [comment]
Eu já estou trabalhando nela ;), o prazo fica para próxima semana.

**Comment by Dovyski** [comment]
Sem problemas, @mateusKoppe, se você já está trabalhando nela pode continuar. Eu faço um PR depois adptando qualquer coisa para usar a API nova. É até mais fácil pra mim 😄

**Comment by mateusKoppe** [comment]
Acabei esquecendo de referenciar a issue no PR.
Essa issue foi concluída no PR #27
