### ISSUE TITLE
[CMS] CRUD do evento

### ISSUE THREAD

**Issue by JeanCHilger** [FronteiraTec/event-manager-uffs#21]
Desenvolver o CRUD para gerenciar as informações do evento.

## Nome do model: 
- `Event`

## Atributos:
- Nome
- Descrição
- Local
- Curso
- Banner
- Dia inicial
- Dia final
- É inscritível

## Requisitos
- [ ] Implementar uma página para listagem;
- [ ] Implementar um formulário para cadastro de evento;
- [ ] Implementar um página para visualizar o evento;
- [ ] Implementar um página para editar evento;
- [ ] Implementar exclusão;
- [ ] Desenvolver validações;
- [ ] Validar autenticação;

**Comment by arufonsekun** [comment]
vou ficar com essa issue, caso todos estiverem de acordo

**Comment by JeanCHilger** [comment]
Algumas considerações: 

- o atributo `sections` começa vazio e aumenta à medida que o usuário adiciona novas seções;
- para o atributo `date` seria interessante dividi-lo em dois outros atributos: `date_start` e `date_end` visto que estes eventos raramente duram apenas um dia.

**Comment by mateusKoppe** [comment]
Fiz umas alterações no requisito da issue

**Comment by JeanCHilger** [comment]
Estou fechando a issue pois iremos criar diversas outras, baseado nos requisitos levantados.
