### ISSUE TITLE
[FRONT] Resolver o conflito de estilos dos cards

### ISSUE THREAD

**Issue by arufonsekun** [FronteiraTec/event-manager-uffs#23]
- O card do login está com alguns estilos definidos no card da home;
 - Será preciso criar um estilo geral e padrão para os cards;
- Verificar que o resource `card.scss` sobrescreve a classe `.card` que é usada no `login.blade.php`;

**Comment by JeanCHilger** [comment]
Por enquanto a tela de login está bugada, então é necessário remover a classe `card__action` dos links do card do login (futuramente este bug será corrigido)
