### ISSUE TITLE
[CMS] Problemas com o layout do login

### ISSUE THREAD

**Issue by arufonsekun** [FronteiraTec/event-manager-uffs#34]
A tela de login não está conforme o layout inicial  e as mensagens de validação estão em inglês, as imagens a seguir mostram como ele está e como deve ficar:

![login-zoado](https://user-images.githubusercontent.com/19571204/76592627-b6bd7200-64d2-11ea-81f6-a301900ddcf3.png)

![login-certo](https://user-images.githubusercontent.com/19571204/76592639-c50b8e00-64d2-11ea-81c6-5b8434872cf5.png)

**Comment by mateusKoppe** [comment]
Posso ficar com essa :D

**Comment by arufonsekun** [comment]
esses problemas no layout eu arrumei na issue do crud do evento, mas depois da nossa reuniao e de ter decidido como o event-manager vai seguir eu acabei deixando de lado o que eu tinha feito, se tu quiser dar uma olhada nesse [commit](https://github.com/arufonsekun/event-manager-uffs/commit/98a0cb6b85b5c2e1a537f2bf08399dbc26ad8cc8) ele arruma essas coisas

**Comment by arufonsekun** [comment]
Nessa issue do CRUD do evento eu precisei sobrescrever essas mensagens de validação tmb, eu tava vendo que dá pra criar um arquivo no caminho `/resources/lang/pt-br/validation.php`, mudar o `locale`pra pt no arquivo `config/app.php` e setar as mensagens em pt-br tudo lá só que o problema é que ele usa o nome das variáveis/atributos pra montar as mensagens que a gente define e que tá em inglês daí trola. A gente tem duas opções em todo CRUD sobrescrever essas mensagens de validação ou setar esse arquivo e achar um jeito de mudar o nome dos atributo pra pt

**Comment by mateusKoppe** [comment]
Não é necessário reescrever em PT os atributos, nos arquivos de traduções tem uma chave `'attributes'` que pode ser usada para traduzir os atributos.
Não encontrei isso na documentação mas encontrei em foruns em uma pesquisa breve que fiz.

**Comment by arufonsekun** [comment]
Meee verdade, tu pode dar um outro nome pro atributo, tava documentado o que o `attributes` faz, nossa trolei demais.
```php
/*
    | The following language lines are used to swap our attribute placeholder
    | with something more reader friendly such as "E-Mail Address" instead
    | of "email". This simply helps us make our message more expressive.
*/
'attributes' => []
```

**Comment by mateusKoppe** [comment]
Eu não encontrei isso na documentação, se você encontrou deixa o link aqui que pode ser útil ;)

**Comment by arufonsekun** [comment]
Acho que na documentação de fato não tem nada sobre isso, mas no resource `resources/lang/en/validation.php`  a partir da [linha 140](https://github.com/fronteiratec/event-manager-uffs/blob/0e47ee1116e3696d445331fe5c8012f7c45be1ce/resources/lang/en/validation.php#L140) está documentado que o array `attributes` pode ser usado para dar um nomes mais user friendly pros nossos atributos
