### ISSUE TITLE
[CMS] Crud de evento

### ISSUE THREAD

**Issue by JeanCHilger** [FronteiraTec/event-manager-uffs#8]
**Esta issue é uma subtarefa da issue #6**

Deverão ser proporcionadas as funcionalidades:
* Cadastrar um novo evento (referente à semana acadêmica), onde fornecerão informações para alilmentar a página do evento, tais como:
  * Nome do evento;
  * Descrição do evento;
  * Serão disponibilizadas várias seções pré-definidas, que o administrador poderá alterar o conteúdo e alguns estilos básicos. As seções a serem desenvolvidas são:
    * Home (issue #16 e #19);
  * Deverá ser permitido também alterar as cores da página;
* Editar as informações listadas;
* Excluir evento;

**Comment by arufonsekun** [comment]
Considerações sobre o que foi decidido no sábado 15/02/2020:
 - Os atributos do model evento são: nome, curso, data, descrição, local;
 - Todo evento terá seções predefinidas, são elas: home, palestrantes, programação, sobre;
- Essa issue deve ser referenciada quando issues derivadas dessa forem criadas;
- O layout de todas essas seções devem estar condizentes;
- Caso surgir alguma dúvida sobre a implementação de alguma dessas seções ela deve ser comentada na issue referente àquela seção;
***OBS***: novos tipos de seções podem surgir ao longo do andamento do projeto, e elas devem ser comentadas aqui;

**Comment by JeanCHilger** [comment]
Pra evitar conflitos ao desenvolver frontends, quem for desenvolver uma issue **[FRONT]** deverá dizer na issue quais arquivos scss serão modificados/usados, assim caso outra pessoa for usar o mesmo arquivo (e estilos) esteja ciente dos possíveis conflitos, e portanto os dois possam conversar/negociar sobre.

**Comment by mateusKoppe** [comment]
Como os requisitos do sistema mudou vou fechar essa issue.
