### ISSUE TITLE
Convenções de código e padrões adotados 

### ISSUE THREAD

**Issue by arufonsekun** [FronteiraTec/event-manager-uffs#9]
* CSS / HTML / Blade:
  * [BEM](http://getbem.com/naming/);
  * Atributos, classes - aspas duplas;
* JavaScript:
  * String - aspas simples;
  * [Google JavaScript Style Guide](https://google.github.io/styleguide/javascriptguide.xml);
  * [Nomes de IDs](https://github.com/FronteiraTec/event-manager-uffs/pull/13#discussion_r376205648);
* PHP:
  * String - aspas simples;
* VueJS:
  * [style guides](https://vuejs.org/v2/style-guide/);
* Nome de branches:
  * [Kebab case](https://en.wiktionary.org/wiki/kebab_case)
  * nome-da-branch;
* Recomenda-se verificar esse [comentário](https://github.com/FronteiraTec/event-manager-uffs/issues/8#issuecomment-587853458) na issue #8, nele há considerações sobre as _issues_ de front-end;

**Comment by JeanCHilger** [comment]
* [*]
  * Identação 4 espaços;

**Comment by Dovyski** [comment]
> * [*]
>   
>   * Identação 4 espaços;

Esse já é um projeto de excelência só por isso. #ficadica.

**Comment by JeanCHilger** [comment]
https://google.github.io/styleguide/javascriptguide.xml

**Comment by arufonsekun** [comment]
Eu acho que seria interessante agente criar um template para a criação de _issues_, a gente até definiu alguns padrões como o prefixo **[FRONT]** ou **[BACK]** no título

**Comment by JeanCHilger** [comment]
De fato seria interessante.

Acho que sempre que for _backend_, a gente especifica o nome de todos os atributos, e do model.

Nas PRs também, sempre devemos referenciar qual issue ela resolve

**Comment by arufonsekun** [comment]
Uma coisa que eu e o @JeanCHilger estávamos conversando hj que talvez seja um padrão que a gente deveria adotar é o [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716). Acho que o @mateusKoppe já usa, alguns projetos que a gente poderia usar como referência são o [Vuejs](https://github.com/vuejs/vue/blob/dev/.github/COMMIT_CONVENTION.md) e o [AngularJS](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md)

**Comment by mateusKoppe** [comment]
Eu acho que vai ser muito bom a gente adotar, ajuda muito a organizar os commits!

**Comment by arufonsekun** [comment]
então está decidido
